accept arguments without requiring input

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,11 +1,13 @@
 #!/bin/bash
 
+# Define variables
 INIT_DIR=$(pwd)
 ALIASES_DIR=./configs/.aliases
 VIMRC=./configs/vimrc
 TMUX_CONF=./configs/tmux.conf
 VIM_BUNDLE_DIR=~/.vim/bundle
 
+# Define functions
 function copy_aliases {
     echo "-- Copying aliases..."
     cd "$INIT_DIR" || exit
@@ -16,7 +18,7 @@ function setup_vim {
     echo "-- Installing vim pathogen..."
     mkdir -p ~/.vim/autoload ~/.vim/bundle
     curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
-    echo "-- Cloning vim packages..." 
+    echo "-- Cloning vim packages..."
     git -C "$VIM_BUNDLE_DIR" clone https://github.com/preservim/nerdtree
     git -C "$VIM_BUNDLE_DIR" clone https://github.com/tpope/vim-surround
     git -C "$VIM_BUNDLE_DIR" clone https://github.com/altercation/vim-colors-solarized
@@ -31,19 +33,44 @@ function setup_tmux {
     cp "$TMUX_CONF" ~/.tmux.conf
 }
 
-# Ask user for input
-read -rp "Add aliases? [y/n] " yn
-if [[ "$yn" =~ ^[Yy]$ ]]; then
-    copy_aliases
+# Parse command-line arguments
+while getopts ":vt" opt; do
+  case $opt in
+    v)
+      setup_vim
+      ;;
+    t)
+      setup_tmux
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      exit 1
+      ;;
+    :)
+      echo "Option -$OPTARG requires an argument." >&2
+      exit 1
+      ;;
+  esac
+done
+
+# If no options are specified, prompt the user
+if [[ $OPTIND -eq 1 ]]; then
+    read -rp "Add aliases? [y/n] " yn
+    if [[ "$yn" =~ ^[Yy]$ ]]; then
+        copy_aliases
+    fi
+
+    read -rp "Setup vim? [y/n] " yn
+    if [[ "$yn" =~ ^[Yy]$ ]]; then
+        setup_vim
+    fi
+
+    read -rp "Setup tmux? [y/n] " yn
+    if [[ "$yn" =~ ^[Yy]$ ]]; then
+        setup_tmux
+    fi
 fi
 
-read -rp "Setup vim? [y/n] " yn
-if [[ "$yn" =~ ^[Yy]$ ]]; then
-    setup_vim
-fi
-
-read -rp "Setup tmux? [y/n] " yn
-if [[ "$yn" =~ ^[Yy]$ ]]; then
-    setup_tmux
-fi
+# Shift the option index so that positional parameters can be used
+shift $((OPTIND -1))
 
